name: Deploy CloudFormation
on: ['push']

jobs:
  build:
    name: CloudFormation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create Change Set
        uses: docker://meredithdigops/digops-stacks:0.19.1
        env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          entrypoint: digops-stacks
          args: change-set test-change template.yml --environment ${GITHUB_REF} --customer test --purpose test --region us-east-1

      - name: Apply Change Set
        uses: docker://meredithdigops/digops-stacks:0.19.1
        env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          entrypoint: digops-stacks
          args: execute test-change --environment ${GITHUB_REF} --region us-east-1
