name: Deploy CloudFormation
on: ['push']

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: docker://meredithdigops/digops-stacks:0.19.1
        with:
          entrypoint: digops-stacks
          args: change-set test template.yml --environment test --customer test --purpose test --region us-east-1
        env:
           AWS_ACCESS_KEY_ID: ${{ secrets. AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
